{% set name = "tecio" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tecio-{{ version }}.tar.gz
  sha256: c89835af0a95bd803b996bcc60be6deb58b50f864b8d014d09febf10a85dc51a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - construct >=2.10.67
    - numpy

test:
  imports:
    - tecio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/luohancfd/tecio
  summary: 'A pure python package to read and write Tecplot binary data'
  description: |
    TecIO is a pure Python package licensed under GPL v3, designed to facilitate
    the reading and writing of data files in the Tecplot binary format.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - luohancfd
